# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/Документы/CV/MathCV

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/Документы/CV/MathCV

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Документы/CV/MathCV/CMakeFiles /home/user/Документы/CV/MathCV//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Документы/CV/MathCV/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MathCV

# Build rule for target.
MathCV: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MathCV
.PHONY : MathCV

# fast build rule for target.
MathCV/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathCV.dir/build.make CMakeFiles/MathCV.dir/build
.PHONY : MathCV/fast

#=============================================================================
# Target rules for targets named test_mathcv

# Build rule for target.
test_mathcv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mathcv
.PHONY : test_mathcv

# fast build rule for target.
test_mathcv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_mathcv.dir/build.make CMakeFiles/test_mathcv.dir/build
.PHONY : test_mathcv/fast

#=============================================================================
# Target rules for targets named UnitTest++

# Build rule for target.
UnitTest++: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UnitTest++
.PHONY : UnitTest++

# fast build rule for target.
UnitTest++/fast:
	$(MAKE) $(MAKESILENT) -f unittest-cpp/CMakeFiles/UnitTest++.dir/build.make unittest-cpp/CMakeFiles/UnitTest++.dir/build
.PHONY : UnitTest++/fast

#=============================================================================
# Target rules for targets named TestUnitTest++

# Build rule for target.
TestUnitTest++: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestUnitTest++
.PHONY : TestUnitTest++

# fast build rule for target.
TestUnitTest++/fast:
	$(MAKE) $(MAKESILENT) -f unittest-cpp/CMakeFiles/TestUnitTest++.dir/build.make unittest-cpp/CMakeFiles/TestUnitTest++.dir/build
.PHONY : TestUnitTest++/fast

MathCVTests.o: MathCVTests.cxx.o
.PHONY : MathCVTests.o

# target to build an object file
MathCVTests.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_mathcv.dir/build.make CMakeFiles/test_mathcv.dir/MathCVTests.cxx.o
.PHONY : MathCVTests.cxx.o

MathCVTests.i: MathCVTests.cxx.i
.PHONY : MathCVTests.i

# target to preprocess a source file
MathCVTests.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_mathcv.dir/build.make CMakeFiles/test_mathcv.dir/MathCVTests.cxx.i
.PHONY : MathCVTests.cxx.i

MathCVTests.s: MathCVTests.cxx.s
.PHONY : MathCVTests.s

# target to generate assembly for a file
MathCVTests.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_mathcv.dir/build.make CMakeFiles/test_mathcv.dir/MathCVTests.cxx.s
.PHONY : MathCVTests.cxx.s

mathcv.o: mathcv.cpp.o
.PHONY : mathcv.o

# target to build an object file
mathcv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathCV.dir/build.make CMakeFiles/MathCV.dir/mathcv.cpp.o
.PHONY : mathcv.cpp.o

mathcv.i: mathcv.cpp.i
.PHONY : mathcv.i

# target to preprocess a source file
mathcv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathCV.dir/build.make CMakeFiles/MathCV.dir/mathcv.cpp.i
.PHONY : mathcv.cpp.i

mathcv.s: mathcv.cpp.s
.PHONY : mathcv.s

# target to generate assembly for a file
mathcv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathCV.dir/build.make CMakeFiles/MathCV.dir/mathcv.cpp.s
.PHONY : mathcv.cpp.s

src/LinearAlgebra/matrix.o: src/LinearAlgebra/matrix.cpp.o
.PHONY : src/LinearAlgebra/matrix.o

# target to build an object file
src/LinearAlgebra/matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathCV.dir/build.make CMakeFiles/MathCV.dir/src/LinearAlgebra/matrix.cpp.o
.PHONY : src/LinearAlgebra/matrix.cpp.o

src/LinearAlgebra/matrix.i: src/LinearAlgebra/matrix.cpp.i
.PHONY : src/LinearAlgebra/matrix.i

# target to preprocess a source file
src/LinearAlgebra/matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathCV.dir/build.make CMakeFiles/MathCV.dir/src/LinearAlgebra/matrix.cpp.i
.PHONY : src/LinearAlgebra/matrix.cpp.i

src/LinearAlgebra/matrix.s: src/LinearAlgebra/matrix.cpp.s
.PHONY : src/LinearAlgebra/matrix.s

# target to generate assembly for a file
src/LinearAlgebra/matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathCV.dir/build.make CMakeFiles/MathCV.dir/src/LinearAlgebra/matrix.cpp.s
.PHONY : src/LinearAlgebra/matrix.cpp.s

src/LinearAlgebra/vector2d.o: src/LinearAlgebra/vector2d.cpp.o
.PHONY : src/LinearAlgebra/vector2d.o

# target to build an object file
src/LinearAlgebra/vector2d.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathCV.dir/build.make CMakeFiles/MathCV.dir/src/LinearAlgebra/vector2d.cpp.o
.PHONY : src/LinearAlgebra/vector2d.cpp.o

src/LinearAlgebra/vector2d.i: src/LinearAlgebra/vector2d.cpp.i
.PHONY : src/LinearAlgebra/vector2d.i

# target to preprocess a source file
src/LinearAlgebra/vector2d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathCV.dir/build.make CMakeFiles/MathCV.dir/src/LinearAlgebra/vector2d.cpp.i
.PHONY : src/LinearAlgebra/vector2d.cpp.i

src/LinearAlgebra/vector2d.s: src/LinearAlgebra/vector2d.cpp.s
.PHONY : src/LinearAlgebra/vector2d.s

# target to generate assembly for a file
src/LinearAlgebra/vector2d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathCV.dir/build.make CMakeFiles/MathCV.dir/src/LinearAlgebra/vector2d.cpp.s
.PHONY : src/LinearAlgebra/vector2d.cpp.s

test.o: test.cpp.o
.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathCV.dir/build.make CMakeFiles/MathCV.dir/test.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_mathcv.dir/build.make CMakeFiles/test_mathcv.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i
.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathCV.dir/build.make CMakeFiles/MathCV.dir/test.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_mathcv.dir/build.make CMakeFiles/test_mathcv.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s
.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathCV.dir/build.make CMakeFiles/MathCV.dir/test.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_mathcv.dir/build.make CMakeFiles/test_mathcv.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... MathCV"
	@echo "... TestUnitTest++"
	@echo "... UnitTest++"
	@echo "... test_mathcv"
	@echo "... MathCVTests.o"
	@echo "... MathCVTests.i"
	@echo "... MathCVTests.s"
	@echo "... mathcv.o"
	@echo "... mathcv.i"
	@echo "... mathcv.s"
	@echo "... src/LinearAlgebra/matrix.o"
	@echo "... src/LinearAlgebra/matrix.i"
	@echo "... src/LinearAlgebra/matrix.s"
	@echo "... src/LinearAlgebra/vector2d.o"
	@echo "... src/LinearAlgebra/vector2d.i"
	@echo "... src/LinearAlgebra/vector2d.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

